---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: snippetbox
  namespace: flux-system
spec:
  path: ./apps/base/snippetbox/terraform
  interval: 10m
  tfstate:
    forceUnlock: auto
  # TODO: Disable auto approve for production.
  approvePlan: auto
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    metadata:
      labels:
        azure.workload.identity/use: "true"
