---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: new-key-vault
  namespace: argo
spec:
  entrypoint: new-key-vault
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: subscription-id
        value: ae9db8ac-2682-4a98-ad36-7d13b2bd5a24
      - name: location
        value: northeurope
      - name: resource-group-name
        value: rg-argo
      - name: key-vault-name-prefix
        value: kv-argo-
  templates:
    - name: new-key-vault
      inputs:
        parameters:
          - name: subscription-id
          - name: location
          - name: resource-group-name
          - name: new-resource-group
          - name: key-vault-name-prefix
      metadata:
        labels:
          azure.workload.identity/use: "true"
      container:
        image: smorenburg/powershell
        command: [ "pwsh" ]
        args: [
          "-Command",
          "New-KeyVault",
          "-ConnectAzure",
          "-SubscriptionId {{inputs.parameters.subscription-id}}",
          "-NewResourceGroup {{inputs.parameters.new-resource-group}}",
          "-Location {{inputs.parameters.location}}",
          "-KeyVaultNamePrefix {{inputs.parameters.key-vault-name-prefix}}"
        ]
