---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: new-virtual-machine
  namespace: argo
spec:
  entrypoint: new-virtual-machine
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: subscription-id
        value: ae9db8ac-2682-4a98-ad36-7d13b2bd5a24
      - name: location
        value: northeurope
      - name: resource-group-name
        value: rg-argo
      - name: virtual-network-resource-group-name
        value: rg-argo-neu
      - name: virtual-network-name
        value: vnet-argo-neu
      - name: subnet-name
        value: default
      - name: key-vault-name
        value: kv-
      - name: new-key-vault
        value: $True
        enum:
          - $True
          - $False
      - name: object-id
        value: de98da92-5d05-4bde-b437-efa11721943a
      - name: virtual-machine-size
        value: Standard_B2s
      - name: image
        value: Ubuntu
  templates:
    - name: new-virtual-machine
      inputs:
        parameters:
          - name: subscription-id
          - name: location
          - name: resource-group-name
          - name: virtual-network-resource-group-name
          - name: virtual-network-name
          - name: subnet-name
          - name: key-vault-name
          - name: object-id
          - name: new-key-vault
          - name: virtual-machine-size
          - name: image
      metadata:
        labels:
          azure.workload.identity/use: "true"
      container:
        image: smorenburg/powershell
        command: [ "pwsh" ]
        args: [
          "-Command",
          "New-VirtualMachine",
          "-ConnectAzure",
          "-SubscriptionId {{inputs.parameters.subscription-id}}",
          "-ResourceGroupName {{inputs.parameters.resource-group-name}}",
          "-Location {{inputs.parameters.location}}",
          "-VirtualNetworkResourceGroupName {{inputs.parameters.virtual-network-resource-group-name}}",
          "-VirtualNetworkName {{inputs.parameters.virtual-network-name}}",
          "-SubnetName {{inputs.parameters.subnet-name}}",
          "-KeyVaultName {{inputs.parameters.key-vault-name}}",
          "-ObjectId {{inputs.parameters.object-id}}",
          "-NewKeyVault {{inputs.parameters.new-key-vault}}",
          "-VirtualMachineSize {{inputs.parameters.virtual-machine-size}}",
          "-Image {{inputs.parameters.image}}"
        ]
