---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: new-resource-group
  namespace: argo
spec:
  entrypoint: new-resource-group
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: subscription-id
        value: ae9db8ac-2682-4a98-ad36-7d13b2bd5a24
      - name: location
        value: northeurope
      - name: resource-group-name
        value: rg-argo
  templates:
    - name: new-resource-group
      inputs:
        parameters:
          - name: subscription-id
          - name: location
          - name: resource-group-name
      metadata:
        labels:
          azure.workload.identity/use: "true"
      container:
        image: smorenburg/powershell
        command: [ "pwsh" ]
        args: [
          "-Command",
          "New-ResourceGroup",
          "-SubscriptionId {{inputs.parameters.subscription-id}}",
          "-Location {{inputs.parameters.location}}",
          "-ResourceGroupName {{inputs.parameters.resource-group-name}}",
          "-ConnectAzure"
        ]
