---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: snippetbox
  namespace: flux-system
spec:
  backendConfig:
    customConfiguration: |
      backend "azurerm" {
        resource_group_name  = "rg-tfstate-astro-neu"
        storage_account_name = "stastrop0ze8b"
        container_name       = "tfstate"
        key                  = "snippetbox.production.northeurope.tfstate"
        use_oidc             = true
      }
  vars:
    - name: environment
      value: production
    - name: resource_group
      value: rg-tfstate-astro-neu
    - name: storage_account
      value: stastrop0ze8b
    - name: container_image
      value: smorenburg/snippetbox:0.0.6
    - name: ingress_rule_host
      value: snippetbox.98.71.67.111.nip.io
  runnerPodTemplate:
    spec:
      env:
        - name: ARM_TENANT_ID
          value: 7ddc4c97-c5a0-4a29-ac83-59be0f280518
        - name: ARM_SUBSCRIPTION_ID
          value: ae9db8ac-2682-4a98-ad36-7d13b2bd5a24
        - name: ARM_CLIENT_ID
          value: f62a5ca0-df2d-4bee-981e-ce5d3c2f9ec3
        - name: ARM_USE_OIDC
          value: "true"
        - name: ARM_OIDC_TOKEN_FILE_PATH
          value: /var/run/secrets/azure/tokens/azure-identity-token
