---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argo
  namespace: argo
spec:
  interval: 24h
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-workflows
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo
      interval: 12h
  values:
    workflow:
      serviceAccount:
        create: true
        name: argo-workflow
      rbac:
        create: true
