---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 24h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 12h
