---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  values:
    server:
      authModes: [ server ]
    workflow:
      serviceAccount:
        annotations:
          azure.workload.identity/client-id: 1e2c07ce-b4df-4283-b74d-27435cb4464f
