---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  values:
    runner:
      serviceAccount:
        annotations:
          azure.workload.identity/client-id: 33bcec27-23d2-42cc-96df-24863ae965f4
