---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  values:
    runner:
      serviceAccount:
        annotations:
          azure.workload.identity/client-id: 35b58507-cd85-48d0-a937-670f3d06ebe7
